freebsd_task:
  matrix:
    - name: FreeBSD 14.1
      freebsd_instance:
        image_family: freebsd-14-1
    - name: FreeBSD 13.3
      freebsd_instance:
        image_family: freebsd-13-3

  env:
    TESTS_REDUCED_KEYLENGTHS: yes
    LEAK_DETECTIVE: no
    MONOLITHIC: no
    TEST: freebsd
    OS_NAME: freebsd

  install_script: ./scripts/test.sh deps
  script: ./scripts/test.sh

alpine_task:
  container:
    image: alpine:latest

  env:
    TESTS_REDUCED_KEYLENGTHS: yes
    TESTS_NO_IPV6: yes
    LEAK_DETECTIVE: no
    MONOLITHIC: no
    TEST: alpine
    OS_NAME: alpine

  install_script: ./scripts/test.sh deps
  script: ./scripts/test.sh
